version: 2.1

workflows:
  maven_test:
    build:
    docker:
      - image: circleci/openjdk:11.0-stretch-node-browsers-legacy
    steps:
      - checkout
      - run : mvn verify sonar:sonar
      

