jobs:
  build:
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      - run: mvn package
      - run: mvn verify sonar:sonar
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
version: 2.1
workflows:
  main:
    jobs:
      - build:
          context: sonarcloud
