jobs:
  build:
    docker:
      - image: 'openjdk:11'
    steps:
      - checkout
      - sonarcloud/scan_with_maven
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
version: 2.1
workflows:
  main:
    jobs:
      - build:
          context: sonarcloud
